name: 'Setup Haskell Stack'
description: 'Setup Haskell and cache dependencies'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2

    - name: Setup Haskell Stack
      uses: actions/setup-haskell@v1
      with:
        ghc-version: 'latest'
        stack-version: 'latest'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-
