name: Haskell Stack Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/setup-haskell-stack

    - name: Stack build
      run: stack build --system-ghc
