name: Haskell Stack Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: ./.github/actions/setup-haskell-stack
    - name: Stack test
      run: stack test --system-ghc
